### ISSUE TITLE
你好，请问做了混淆吗

### ISSUE THREAD

**Issue by biqinglin** [cyanzhong/RuntimeInvoker#4]
想问的是：使用此工具是否能绕过苹果审核

**Comment by welcommand** [comment]
亲测可以 :)

**Comment by biqinglin** [comment]
你好。。。可以求个联系嘛？有些问题想请教，或者您加我：931237936 备注：ios

**Comment by cyanzhong** [comment]
这个项目本身并不需要做什么混淆，但是如果你的 selector 是一些敏感 API 的话，你应该知道会发生什么。
